name = "matzip-api"
main = "src/worker.js"
compatibility_date = "2024-09-19"
assets = { directory = "dist" }

[[d1_databases]]
binding = "DB"
database_name = "matzip"
database_id = "a79357b7-0549-4b73-a8de-391455a00bf9"
